-- 0002_rider_platform.sql

ALTER TABLE riders
  ADD COLUMN IF NOT EXISTS supabase_user_id UUID UNIQUE, -- nullable: riders may exist without auth account
  ADD COLUMN IF NOT EXISTS avatar_url        TEXT,
  ADD COLUMN IF NOT EXISTS preferred_locale  VARCHAR(2)  NOT NULL DEFAULT 'vi',
  ADD COLUMN IF NOT EXISTS tier              VARCHAR(10) NOT NULL DEFAULT 'free'
    CHECK (tier IN ('free', 'premium')),
  ADD COLUMN IF NOT EXISTS last_active_at    TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS rider_sessions (
  id           UUID        PRIMARY KEY, -- generated by app layer (UUID v7 via uuid crate)
  rider_id     UUID        NOT NULL REFERENCES riders(id) ON DELETE CASCADE,
  session_type VARCHAR(20) NOT NULL
    CHECK (session_type IN ('fit','aero','race_plan','comparison')),
  payload      JSONB       NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rider_sessions_rider ON rider_sessions(rider_id, created_at DESC);
